### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 47

### ISSUE THREAD

**Issue by netbe** [sinnerschrader-mobile/metaJSON#9]
Got an error on a json file containing a description with special character, like : **Geräteeinstellung.**

Here's the trace:

```
Traceback (most recent call last):
  File "submodules/metaJSON/readJSON.py", line 163, in <module>
    if schemeObj.parseDictionary(dic) == False:
  File "/Users/netbe/code/egym-trainer-ios-internal/submodules/metaJSON/JSONScheme.py", line 505, in parseDictionary
    tmpPropList = self.parseProperty(jsonDic['property'])
  File "/Users/netbe/code/egym-trainer-ios-internal/submodules/metaJSON/JSONScheme.py", line 434, in parseProperty
    newProp = self.makeNewScheme(dic)
  File "/Users/netbe/code/egym-trainer-ios-internal/submodules/metaJSON/JSONScheme.py", line 324, in makeNewScheme
    if newScheme.parseDictionary(jsonDic) :
  File "/Users/netbe/code/egym-trainer-ios-internal/submodules/metaJSON/JSONScheme.py", line 476, in parseDictionary
    self.type_description = str(jsonDic['description'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 47: ordinal not in range(128)
```

**Comment by SanggeonPark** [comment]
to resolve that problem, we need to upgrade python version. I'll try out to find other solutions.

**Comment by netbe** [comment]
@SanggeonPark is it still valid? 
Which version of python is touched?
And this is for [v0.9.1](https://github.com/sinnerschrader-mobile/metaJSON/tree/v0.9.1) or master I presume?

**Comment by SanggeonPark** [comment]
I think.. it's not, with Python 2.7.6 it works....
